/* Shule AI v46 — Approved Simple Student/Teacher View + Edit UI
   Light/dark adaptive, no layout changes outside approved modals. */
.approved-modal-overlay{position:fixed;inset:0;z-index:9999;background:rgba(15,23,42,.58);backdrop-filter:blur(10px);display:flex;align-items:center;justify-content:center;padding:20px;overflow:auto}
.approved-modal{width:min(980px,100%);max-height:92vh;overflow:auto;border-radius:22px;border:1px solid var(--approved-border,#e5e7eb);background:var(--approved-card,#fff);color:var(--approved-text,#0f172a);box-shadow:0 28px 80px rgba(2,6,23,.28)}
.approved-modal.simple{width:min(760px,100%)}
.approved-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:18px 22px;border-bottom:1px solid var(--approved-border,#e5e7eb);background:var(--approved-card,#fff)}
.approved-title{font-size:20px;font-weight:900;letter-spacing:-.02em;margin:0}.approved-subtitle{font-size:13px;color:var(--approved-muted,#64748b);margin-top:2px}.approved-close{height:36px;width:36px;border:1px solid var(--approved-border,#e5e7eb);border-radius:12px;background:transparent;color:inherit;font-size:22px;line-height:1;cursor:pointer}.approved-body{padding:22px}.approved-foot{display:flex;align-items:center;justify-content:flex-end;gap:10px;padding:16px 22px;border-top:1px solid var(--approved-border,#e5e7eb);background:var(--approved-soft,#f8fafc)}
.approved-profile-row{display:grid;grid-template-columns:92px 1fr;gap:18px;align-items:center;margin-bottom:20px}.approved-avatar{height:82px;width:82px;border-radius:22px;overflow:hidden;background:linear-gradient(135deg,#2563eb,#7c3aed);display:grid;place-items:center;color:white;font-weight:900;font-size:24px;box-shadow:0 12px 28px rgba(37,99,235,.22)}.approved-avatar img{height:100%;width:100%;object-fit:cover}.approved-name{font-size:26px;font-weight:900;letter-spacing:-.03em;margin:0}.approved-meta{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px}.approved-pill{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:5px 10px;font-size:12px;font-weight:800;background:var(--approved-pill,#eef2ff);color:var(--approved-pill-text,#4338ca)}
.approved-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.approved-grid.three{grid-template-columns:repeat(3,minmax(0,1fr))}.approved-card{border:1px solid var(--approved-border,#e5e7eb);border-radius:16px;background:var(--approved-soft,#f8fafc);padding:14px}.approved-label{display:block;font-size:12px;font-weight:800;color:var(--approved-muted,#64748b);text-transform:uppercase;letter-spacing:.04em;margin-bottom:5px}.approved-value{font-size:15px;font-weight:800;color:var(--approved-text,#0f172a);word-break:break-word}.approved-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.approved-field label{display:block;font-size:12px;font-weight:800;color:var(--approved-muted,#64748b);margin-bottom:6px}.approved-field input,.approved-field select,.approved-field textarea{width:100%;border:1px solid var(--approved-border,#e5e7eb);border-radius:13px;background:var(--approved-input,#fff);color:var(--approved-text,#0f172a);padding:11px 12px;outline:none}.approved-field textarea{min-height:88px;resize:vertical}.approved-field input:focus,.approved-field select:focus,.approved-field textarea:focus{border-color:#7c3aed;box-shadow:0 0 0 3px rgba(124,58,237,.14)}.approved-span-2{grid-column:span 2}.approved-btn{border:1px solid var(--approved-border,#e5e7eb);background:var(--approved-card,#fff);color:var(--approved-text,#0f172a);border-radius:13px;padding:10px 14px;font-weight:800;cursor:pointer}.approved-btn.primary{border-color:#7c3aed;background:#7c3aed;color:white}.approved-btn.danger{border-color:#fecaca;background:#fef2f2;color:#b91c1c}.approved-table-card{border:1px solid var(--approved-border,#e5e7eb);border-radius:18px;overflow:hidden;background:var(--approved-card,#fff)}.approved-table{width:100%;border-collapse:collapse}.approved-table th,.approved-table td{padding:12px 14px;text-align:left;border-bottom:1px solid var(--approved-border,#e5e7eb);font-size:14px}.approved-table th{background:var(--approved-soft,#f8fafc);font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:var(--approved-muted,#64748b)}.approved-actions{display:flex;gap:8px;flex-wrap:wrap}
.dark .approved-modal,[data-theme="dark"] .approved-modal,body.dark .approved-modal{--approved-card:#0f172a;--approved-soft:#111827;--approved-input:#020617;--approved-border:#243244;--approved-text:#e5e7eb;--approved-muted:#94a3b8;--approved-pill:#312e81;--approved-pill-text:#ddd6fe}.dark .approved-head,[data-theme="dark"] .approved-head,body.dark .approved-head{background:#0f172a}.dark .approved-foot,[data-theme="dark"] .approved-foot,body.dark .approved-foot{background:#111827}.dark .approved-btn.danger,[data-theme="dark"] .approved-btn.danger,body.dark .approved-btn.danger{background:#450a0a;border-color:#7f1d1d;color:#fecaca}
@media(max-width:760px){.approved-profile-row{grid-template-columns:1fr;text-align:left}.approved-grid,.approved-grid.three,.approved-form-grid{grid-template-columns:1fr}.approved-span-2{grid-column:auto}.approved-modal{max-height:94vh}.approved-body{padding:16px}.approved-head,.approved-foot{padding:14px 16px}.approved-name{font-size:22px}}
