// chat-v9-ui.js — v68 production messaging workspace (full module, no compatibility shim)
(function(){
  const $ = id => document.getElementById(id);
  const api = () => window.chatV9API;
  const appState = {
    role: 'student', tab: 'study', selectedGroupId: null, selectedThreadId: null, selectedPeerId: null, selectedChildId: null,
    groups: [], threads: [], replies: {}, peers: [], members: [], messages: [], children: [], contacts: [], query: '', attachment: null, replyTo: null,
    recorder: null, chunks: [], recording: false, unread: {}, typingTimer: null, typingText: '', loadedAt: Date.now()
  };
  const esc = s => String(s ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const toast = (m,t='info') => typeof showToast === 'function' ? showToast(m,t) : console[t==='error'?'error':'log'](m);
  const media = u => (typeof resolveMediaUrl === 'function' ? resolveMediaUrl(u) : u);
  const currentUser = () => { try { return JSON.parse(localStorage.getItem('user') || localStorage.getItem('shule_user') || '{}'); } catch { return {}; } };
  const initials = n => String(n||'?').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
  const avatar = (u={}, cls='') => u.profileImage ? `<img class="v68-avatar ${cls}" src="${esc(media(u.profileImage))}" alt="${esc(u.name||'User')}">` : `<span class="v68-avatar ${cls}">${initials(u.name)}</span>`;
  const time = d => d ? new Date(d).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'}) : '';
  const date = d => d ? new Date(d).toLocaleDateString() : '';
  const metaOf = row => row?.metadata || {};
  const fileLink = (url, name='Attachment') => url ? `<a class="v68-file" href="${esc(media(url))}" target="_blank" rel="noopener">📎 ${esc(name)}</a>` : '';
  const currentGroup = () => appState.groups.find(g => String(g.id) === String(appState.selectedGroupId)) || appState.groups[0] || null;
  const currentThread = () => appState.threads.find(t => Number(t.id) === Number(appState.selectedThreadId)) || appState.threads[0] || null;
  const currentPeer = () => appState.peers.find(p => Number(p.id) === Number(appState.selectedPeerId)) || appState.peers[0] || null;
  const currentChild = () => appState.children.find(c => Number(c.id) === Number(appState.selectedChildId)) || appState.children[0] || null;
  const threadReplies = t => t ? (t.ThreadReplies || t.replies || appState.replies[t.id] || []) : [];
  const isApproved = t => (metaOf(t).approvalStatus || (t.Creator?.role === 'student' ? 'pending' : 'approved')) === 'approved';
  const isPending = t => (metaOf(t).approvalStatus || '').toLowerCase() === 'pending';

  function shell(title, subtitle, actions, rootId){
    return `<section class="v68-page">
      <header class="v68-top"><div><p class="v68-kicker">Communication</p><h2>${esc(title)}</h2><small>${esc(subtitle)}</small></div><div class="v68-top-actions">${actions||''}</div></header>
      <div id="${rootId}" class="v68-shell"><div class="v68-empty">Loading...</div></div>
    </section>`;
  }
  function tabs(list){ return `<nav class="v68-tabs">${list.map(([k,l])=>`<button class="${appState.tab===k?'active':''}" onclick="v68SetTab('${k}')">${l}</button>`).join('')}</nav>`; }
  function listItem(item, active, onclick, sub, icon='👤', badge=''){
    return `<button class="v68-list-item ${active?'active':''}" onclick="${onclick}"><span class="v68-list-icon">${icon}</span><span class="v68-list-text"><b>${esc(item.name||item.topic||item.displayName||'Untitled')}</b><small>${esc(sub||'')}</small></span>${badge}</button>`;
  }
  function messageBubble(row, opts={}){
    const me = currentUser(); const sender = row.Sender || row.Author || row.sender || (Number(row.senderId||row.userId)===Number(me.id) ? me : {});
    const mine = Number(sender.id || row.senderId || row.userId) === Number(me.id);
    const md = metaOf(row); const reactions = md.reactions || {}; const pinned = md.pinned; const reply = md.replyTo;
    const attachmentUrl = row.attachmentUrl || md.attachmentUrl; const attachmentName = md.attachmentName || md.attachment?.name || 'Attachment';
    const isTeacher = sender.role === 'teacher'; const label = isTeacher ? '<em>Teacher</em>' : sender.role === 'student' ? '<em>Student</em>' : sender.role ? `<em>${esc(sender.role)}</em>` : '';
    return `<article class="v68-msg ${mine?'mine':''} ${pinned?'pinned':''}">${!mine?avatar(sender,'sm'):''}<div class="v68-bubble ${mine?'mine':''}">
      ${!mine?`<strong>${esc(sender.name||'User')} ${label}</strong>`:''}${pinned?'<div class="v68-pin">📌 Pinned</div>':''}
      ${reply?`<div class="v68-quote">↪ ${esc(reply.text||'Replied message')}</div>`:''}
      <p>${esc(row.content||'')}</p>${fileLink(attachmentUrl, attachmentName)}
      <div class="v68-reactions">${Object.entries(reactions).map(([e,u])=>`<button onclick="${opts.reply?'v68ReactReply':'v68React'}(${Number(row.id)},'${esc(e)}')">${esc(e)} ${(u||[]).length}</button>`).join('')}</div>
      <div class="v68-meta"><span>${time(row.createdAt)}</span>${mine?'<span title="Read receipt">✓✓</span>':''}${row.pointsAwarded?`<span>⭐ ${row.pointsAwarded}</span>`:''}${row.streakAwarded?`<span>🔥 ${row.streakAwarded}</span>`:''}</div>
      <div class="v68-mini-actions"><button onclick="v68Reply(${Number(row.id)},'${esc(sender.name||'User').replace(/'/g,'&#39;')}','${esc(row.content||'').replace(/'/g,'&#39;')}')">Reply</button><button onclick="${opts.reply?'v68ReactReply':'v68React'}(${Number(row.id)},'👍')">👍</button><button onclick="${opts.reply?'v68ReactReply':'v68React'}(${Number(row.id)},'❤️')">❤️</button><button onclick="${opts.reply?'v68PinReply':'v68Pin'}(${Number(row.id)})">Pin</button>${opts.reward?`<button onclick="${opts.reply?'v68AwardReply':'v68AwardMessage'}(${Number(row.id)},1,0)">⭐</button><button onclick="${opts.reply?'v68AwardReply':'v68AwardMessage'}(${Number(row.id)},5,1)">🔥</button>`:''}<button onclick="${opts.reply?'v68ModerateReply':'v68Moderate'}(${Number(row.id)})">Report</button></div>
    </div></article>`;
  }
  function composer(kind, id){
    const reply = appState.replyTo ? `<div class="v68-replying">Replying to <b>${esc(appState.replyTo.name)}</b>: ${esc(appState.replyTo.text).slice(0,90)} <button onclick="v68CancelReply()">×</button></div>` : '';
    const file = appState.attachment ? `<div class="v68-selected-file">${fileLink(appState.attachment.url, appState.attachment.name)} <button onclick="v68ClearFile()">×</button></div>` : '';
    return `<footer class="v68-composer">${reply}${file}<div id="v68-typing-line" class="v68-typing">${esc(appState.typingText||'')}</div><div class="v68-compose-row"><button onclick="v68Emoji('${kind}','${id}','😊')">😊</button><button onclick="v68PickFile()">📎</button><button class="${appState.recording?'recording':''}" onclick="v68ToggleVoice()">🎙</button><input id="v68-input-${kind}-${id}" placeholder="Type a message..." oninput="v68Typing()" onkeydown="if(event.key==='Enter')v68Send('${kind}','${id}')"><button class="send" onclick="v68Send('${kind}','${id}')">➤</button><input id="v68-file-input" type="file" class="hidden" onchange="v68UploadFile(this.files[0])"></div></footer>`;
  }
  function scrollBottom(){ setTimeout(()=>{ const el=$('v68-feed'); if(el) el.scrollTop=el.scrollHeight; },70); }

  async function uploadAny(file){ if(!file) return null; const fd=new FormData(); fd.append('file',file); const res=await api().uploadAttachment(fd); const data=res.data||res; return { url:data.url||data.fileUrl||data.path, name:file.name, mimeType:file.type, size:file.size }; }

  // STUDENT
  window.renderStudentV9Classroom = async function(){ setTimeout(v68LoadStudent,60); return shell('Study Chats','Simple WhatsApp-style class groups, private messages, teacher topics and student topics.','<button class="v68-btn" onclick="v68LoadStudent()">Refresh</button><button class="v68-btn primary" onclick="v68OpenTopicModal()">+ Topic</button>','v68-student-root'); };
  window.v68LoadStudent = async function(){ appState.role='student'; const root=$('v68-student-root'); if(root) root.innerHTML='<div class="v68-empty">Loading chats...</div>'; try{ const [threadsRes, achRes] = await Promise.all([api().getClassroomThreads(), api().getMyAchievements().catch(()=>({data:{totals:{}}}))]); appState.threads = threadsRes.data || []; const meta=threadsRes.meta||{}; appState.groups = meta.groups || []; const participants = Object.values(meta.participantsByClass||{}).flat(); const me=currentUser(); appState.peers = participants.filter(p=>Number(p.id)!==Number(me.id)); if(!appState.groups.length){ appState.groups=[{id:'my-class',name:'My Class Study Group',participantCount:appState.peers.length+1,participants:[me,...appState.peers]}]; } if(!appState.selectedGroupId) appState.selectedGroupId=appState.groups[0]?.id; if(!appState.selectedThreadId) appState.selectedThreadId=appState.threads[0]?.id; if(!appState.selectedPeerId) appState.selectedPeerId=appState.peers[0]?.id; appState.achievements=achRes.data||{}; v68RenderStudent(); }catch(e){ if(root) root.innerHTML=`<div class="v68-empty error">${esc(e.message||'Could not load chats')}</div>`; } };
  function v68RenderStudent(){ const root=$('v68-student-root'); if(!root)return; const g=currentGroup(); const t=currentThread(); const list=appState.tab==='private'?appState.peers:appState.groups; root.innerHTML=`<div class="v68-main-grid student">${leftPanel(list)}<section class="v68-chat-panel">${tabs([['study','Study Group'],['private','Private']])}${appState.tab==='private'?privateWindow(currentPeer()):studyWindow(g,t,false)}</section><aside class="v68-info-panel">${appState.tab==='private'?privateInfo(currentPeer()):studyInfo(g,t)}</aside></div>`; scrollBottom(); }
  function leftPanel(list){ const q=appState.query.toLowerCase(); const items=(list||[]).filter(x=>!q||String(x.name||'').toLowerCase().includes(q)); return `<aside class="v68-list-panel"><div class="v68-panel-title"><h3>${appState.tab==='private'?'Classmates':'Study Groups'}</h3><small>${items.length} found</small></div><input class="v68-search" placeholder="Search chats..." oninput="v68Search(this.value)">${items.map(x=>appState.tab==='private'?listItem(x,Number(appState.selectedPeerId)===Number(x.id),`v68SelectPeer(${Number(x.id)})`,'Private message','👤', appState.unread[x.id]?`<b class="v68-unread">${appState.unread[x.id]}</b>`:''):listItem(x,String(appState.selectedGroupId)===String(x.id),`v68SelectGroup('${x.id}')`,`${x.participantCount||x.participants?.length||0} participants`,'👥')).join('')||'<div class="v68-empty small">No chats yet.</div>'}</aside>`; }
  function studyWindow(g,t,teacherMode){ const threads=(appState.threads||[]).filter(x=>!g?.classId||Number(x.classId)===Number(g.classId)); const visible=teacherMode?threads:threads.filter(x=>isApproved(x)||Number(x.createdBy)===Number(currentUser().id)); const replies=threadReplies(t); return `<header class="v68-chat-head"><div>${avatar({name:g?.name||'Study'},'group')}<div><h3>${esc(g?.name||'Class Study Group')}</h3><p><span class="v68-online"></span>${g?.participantCount||g?.participants?.length||0} participants • online now</p></div></div><button onclick="v68OpenTopicModal()">+ Topic</button></header><div class="v68-subtabs">${visible.map(x=>`<button class="${Number(x.id)===Number(t?.id)?'active':''}" onclick="v68SelectThread(${Number(x.id)})">${isPending(x)?'⏳ ':''}${esc(x.topic)}</button>`).join('')||'<span>No topics yet</span>'}</div><main id="v68-feed" class="v68-feed">${t?`<div class="v68-topic-card"><b>${esc(t.topic)}</b><p>${esc(t.content)}</p><small>${esc(t.subject||'General')} • ${esc(t.Creator?.name||'Teacher/Student')} • ${isPending(t)?'Waiting for teacher approval':'Open'}</small></div>`:''}${replies.map(r=>messageBubble(r,{reply:true,reward:teacherMode && r.Author?.role==='student'})).join('')||'<div class="v68-empty small">Start the discussion.</div>'}</main>${t?composer('thread',t.id):''}`; }
  function privateWindow(p){ if(!p)return `<div class="v68-empty">Choose a classmate.</div>`; return `<header class="v68-chat-head"><div>${avatar(p)}<div><h3>${esc(p.name)}</h3><p><span class="v68-online"></span>Online • classmate</p></div></div></header><main id="v68-feed" class="v68-feed">${(appState.messages||[]).map(m=>messageBubble(m)).join('')||'<div class="v68-empty small">No private messages yet.</div>'}</main>${composer('direct',p.id)}`; }
  function studyInfo(g,t){ const members=(g?.participants||[]); return `<h3>Participants</h3><div class="v68-member-stack">${members.map(m=>`<div>${avatar(m,'xs')}<span>${esc(m.name)}</span><small>${esc(m.role||'student')}</small></div>`).join('')||'<p>No participants loaded.</p>'}</div><hr><h3>Achievements</h3><p>⭐ ${appState.achievements?.totals?.points||0} points</p><p>🔥 ${appState.achievements?.totals?.streak||0} streaks</p>${t?`<hr><h3>Topic</h3><p>${esc(t.topic)}</p>`:''}`; }
  function privateInfo(p){ return p?`<h3>Private Chat</h3>${avatar(p,'lg')}<h4>${esc(p.name)}</h4><p>${esc(p.role||'student')}</p><button class="v68-btn" onclick="v68LoadDirect(${Number(p.id)})">Refresh messages</button>`:'<p>Select a contact.</p>'; }

  // TEACHER
  window.renderTeacherV9Messages = async function(){ setTimeout(v68LoadTeacher,60); return shell('Messages & Study Rooms','Clean teacher communication, groups, parent chats, moderation and student rewards.','<button class="v68-btn" onclick="v68LoadTeacher()">Refresh</button><button class="v68-btn primary" onclick="v68TeacherNew()">+ New</button>','v68-teacher-root'); };
  window.v68LoadTeacher = async function(){ appState.role='teacher'; const root=$('v68-teacher-root'); if(root) root.innerHTML='<div class="v68-empty">Loading teacher messages...</div>'; try{ const [groups, teachers, threads] = await Promise.all([api().getTeacherGroups(), api().getTeachers(), api().getClassroomThreads()]); appState.groups=groups.data||[]; appState.peers=teachers.data||[]; appState.threads=threads.data||[]; if(!appState.selectedGroupId)appState.selectedGroupId=appState.groups[0]?.id; if(!appState.selectedPeerId)appState.selectedPeerId=appState.peers[0]?.id; if(!appState.selectedThreadId)appState.selectedThreadId=appState.threads[0]?.id; v68RenderTeacher(); }catch(e){ if(root)root.innerHTML=`<div class="v68-empty error">${esc(e.message)}</div>`; } };
  function v68RenderTeacher(){ const root=$('v68-teacher-root'); if(!root)return; const list=appState.tab==='direct'?appState.peers:appState.tab==='study'?appState.threads:appState.groups; root.innerHTML=`<div class="v68-main-grid teacher">${teacherLeft(list)}<section class="v68-chat-panel">${tabs([['groups','Groups'],['study','Study Rooms'],['direct','Direct'],['announce','Announcements']])}${teacherCenter()}</section><aside class="v68-info-panel">${teacherInfo()}</aside></div>`; scrollBottom(); }
  function teacherLeft(list){ const q=appState.query.toLowerCase(); const items=(list||[]).filter(x=>!q||String(x.name||x.topic||'').toLowerCase().includes(q)); return `<aside class="v68-list-panel"><div class="v68-panel-title"><h3>${appState.tab==='study'?'Study Topics':appState.tab==='direct'?'Teachers':'Groups'}</h3><small>${items.length}</small></div><input class="v68-search" placeholder="Search..." oninput="v68Search(this.value)">${items.map(x=> appState.tab==='study'?listItem(x,Number(appState.selectedThreadId)===Number(x.id),`v68SelectThread(${Number(x.id)})`,`${esc(x.subject||'General')} • ${x.studentCount||0} students`,isPending(x)?'⏳':'🧵'):appState.tab==='direct'?listItem(x,Number(appState.selectedPeerId)===Number(x.id),`v68SelectPeer(${Number(x.id)})`,x.role||'teacher','👤'):listItem(x,Number(appState.selectedGroupId)===Number(x.id),`v68SelectGroup(${Number(x.id)})`,x.type||'group','👥')).join('')||'<div class="v68-empty small">Nothing here yet.</div>'}</aside>`; }
  function teacherCenter(){ if(appState.tab==='study')return studyWindow({name:'Study Rooms',participants:[]}, currentThread(), true); if(appState.tab==='direct')return privateWindow(currentPeer()); if(appState.tab==='announce')return `<div class="v68-announcement"><h3>School Announcement</h3><p>Broadcast a message to students, parents or staff.</p><textarea id="v68-announcement-text" placeholder="Write announcement..."></textarea><div><button class="v68-btn">Save Draft</button><button class="v68-btn primary" onclick="v68Broadcast()">Broadcast</button></div></div>`; const g=currentGroup(); return `<header class="v68-chat-head"><div>${avatar({name:g?.name||'Group'},'group')}<div><h3>${esc(g?.name||'Group')}</h3><p><span class="v68-online"></span>${esc(g?.type||'group')} • members managed by teacher</p></div></div><button onclick="v68OpenMembersModal(${Number(g?.id||0)})">Manage Members</button></header><main id="v68-feed" class="v68-feed">${(appState.messages||[]).map(m=>messageBubble(m,{reward:m.Sender?.role==='student'})).join('')||'<div class="v68-empty small">Open or send messages.</div>'}</main>${g?composer('group',g.id):''}`; }
  function teacherInfo(){ if(appState.tab==='study'){ const t=currentThread(); const replies=threadReplies(t); return `<h3>Thread Monitoring</h3><p>${replies.length} replies</p><p>${replies.filter(r=>r.Author?.role==='student').length} student responses</p>${t&&isPending(t)?`<button class="v68-btn primary" onclick="v68ApproveThread(${Number(t.id)})">Approve Topic</button>`:''}${t?`<button class="v68-btn" onclick="v68ToggleThread(${Number(t.id)},${!t.isClosed})">${t.isClosed?'Reopen':'Close'} Thread</button>`:''}<button class="v68-btn" onclick="v68OpenTopicModal()">Create Topic</button>`; } if(appState.tab==='groups'){ const g=currentGroup(); return `<h3>Group Controls</h3><button class="v68-btn" onclick="v68OpenMembersModal(${Number(g?.id||0)})">Manage Members</button><button class="v68-btn" onclick="v68PickFile()">Attach File</button><p>Students receive stars/streaks. Teachers receive emoji reactions only.</p>`; } return `<h3>Controls</h3><p>Use reply, reactions, attachments, read receipts and safe moderation.</p>`; }

  // PARENT
  window.renderParentV68Messages = async function(){ setTimeout(v68LoadParent,60); return shell('Parent Messages','Child-specific conversations with teachers and school admins.','<button class="v68-btn" onclick="v68LoadParent()">Refresh</button>','v68-parent-root'); };
  window.v68LoadParent = async function(){ appState.role='parent'; const root=$('v68-parent-root'); if(root)root.innerHTML='<div class="v68-empty">Loading parent messages...</div>'; try{ const [children, contacts] = await Promise.all([window.api?.parent?.getChildren?.() || apiRequest('/api/parent/children'), api().getParentContacts()]); appState.children=children.data||[]; appState.contacts=contacts.data||[]; appState.peers=appState.contacts; if(!appState.selectedChildId)appState.selectedChildId=appState.children[0]?.id; if(!appState.selectedPeerId)appState.selectedPeerId=appState.contacts[0]?.id; v68RenderParent(); }catch(e){ if(root)root.innerHTML=`<div class="v68-empty error">${esc(e.message)}</div>`; } };
  function v68RenderParent(){ const root=$('v68-parent-root'); if(!root)return; root.innerHTML=`<div class="v68-main-grid parent"><aside class="v68-list-panel"><div class="v68-panel-title"><h3>Children</h3><small>Switch instantly</small></div>${(appState.children||[]).map(c=>listItem({name:c.User?.name||c.name||'Child'},Number(appState.selectedChildId)===Number(c.id),`v68SelectChild(${Number(c.id)})`,c.grade||c.className||'Student','🎒')).join('')||'<div class="v68-empty small">No linked children.</div>'}<hr><h3>Teachers</h3>${(appState.contacts||[]).map(p=>listItem(p,Number(appState.selectedPeerId)===Number(p.id),`v68SelectPeer(${Number(p.id)})`,p.role||'teacher','👤')).join('')}</aside><section class="v68-chat-panel">${tabs([['direct','Teacher Chat']])}${privateWindow(currentPeer())}</section><aside class="v68-info-panel"><h3>Viewing Child</h3><p>${esc(currentChild()?.User?.name||currentChild()?.name||'Select child')}</p><p>Messages are tagged to this child for clean parent-teacher context.</p></aside></div>`; scrollBottom(); }

  // Actions
  window.v68SetTab = k => { appState.tab=k; appState.query=''; appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); };
  window.v68Search = q => { appState.query=q||''; appState.role==='teacher'?v68RenderTeacher():v68RenderStudent(); };
  window.v68SelectGroup = async id => { appState.selectedGroupId=id; if(appState.role==='teacher') await v68LoadGroup(id); else v68RenderStudent(); };
  window.v68SelectThread = id => { appState.selectedThreadId=id; appState.role==='teacher'?v68RenderTeacher():v68RenderStudent(); };
  window.v68SelectPeer = async id => { appState.selectedPeerId=id; await v68LoadDirect(id); };
  window.v68SelectChild = id => { appState.selectedChildId=id; v68RenderParent(); };
  window.v68LoadGroup = async id => { try{ const [msgs, mem] = await Promise.all([api().getGroupMessages(id), api().getGroupMembers(id).catch(()=>({data:[]}))]); appState.messages=msgs.data||[]; appState.members=mem.data||[]; v68RenderTeacher(); }catch(e){ toast(e.message,'error'); } };
  window.v68LoadDirect = async id => { try{ const res=await api().getDirectMessages(id); appState.messages=res.data||[]; if(appState.messages.length) appState.messages.forEach(m=>{ if(Number(m.receiverId)===Number(currentUser().id)) api().markMessageRead(m.id).catch(()=>{}); }); appState.role==='parent'?v68RenderParent():appState.role==='teacher'?v68RenderTeacher():v68RenderStudent(); }catch(e){ toast(e.message,'error'); } };
  window.v68Typing = () => { appState.typingText='Typing...'; const line=$('v68-typing-line'); if(line)line.textContent='Typing...'; clearTimeout(appState.typingTimer); appState.typingTimer=setTimeout(()=>{appState.typingText=''; const l=$('v68-typing-line'); if(l)l.textContent='';},900); };
  window.v68Reply = (id,name,text) => { appState.replyTo={id,name,text}; appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); };
  window.v68CancelReply = () => { appState.replyTo=null; appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); };
  window.v68Emoji = (kind,id,emoji) => { const input=$(`v68-input-${kind}-${id}`); if(input){ input.value += emoji; input.focus(); } };
  window.v68PickFile = () => $('v68-file-input')?.click();
  window.v68UploadFile = async file => { try{ appState.attachment=await uploadAny(file); toast('Attachment ready','success'); appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); }catch(e){ toast(e.message,'error'); } };
  window.v68ClearFile = () => { appState.attachment=null; appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); };
  window.v68Send = async (kind,id) => { const input=$(`v68-input-${kind}-${id}`); const content=(input?.value||'').trim(); const att=appState.attachment; if(!content&&!att)return; try{ if(kind==='thread') await api().replyToThread(id, content || 'Attachment', null, att?.url||null, att||null, appState.replyTo); else if(kind==='group') await api().sendGroupMessage(id, content || 'Attachment', att?.url||null, att||null, appState.replyTo); else await api().sendDirectMessage(id, content || 'Attachment', att?.url||null, att||null, { ...(appState.replyTo||{}), childId: appState.selectedChildId||null }); input.value=''; appState.attachment=null; appState.replyTo=null; if(kind==='thread'){ appState.role==='teacher'?await v68LoadTeacher():await v68LoadStudent(); } else if(kind==='group') await v68LoadGroup(id); else await v68LoadDirect(id); }catch(e){ toast(e.message,'error'); } };
  window.v68React = async (id,e) => { try{ await api().reactToMessage(id,e); appState.tab==='groups'?await v68LoadGroup(appState.selectedGroupId):await v68LoadDirect(appState.selectedPeerId); }catch(err){ toast(err.message,'error'); } };
  window.v68ReactReply = async (id,e) => { try{ await api().reactToReply(id,e); appState.role==='teacher'?await v68LoadTeacher():await v68LoadStudent(); }catch(err){ toast(err.message,'error'); } };
  window.v68Pin = async id => { try{ await api().pinMessage(id); appState.tab==='groups'?await v68LoadGroup(appState.selectedGroupId):await v68LoadDirect(appState.selectedPeerId); }catch(e){ toast(e.message,'error'); } };
  window.v68PinReply = async id => { try{ await api().pinReply(id); appState.role==='teacher'?await v68LoadTeacher():await v68LoadStudent(); }catch(e){ toast(e.message,'error'); } };
  window.v68Moderate = async id => { try{ await api().moderateMessage(id,{action:'reported',reason:'Reported from chat'}); toast('Reported to moderation','success'); }catch(e){ toast(e.message,'error'); } };
  window.v68ModerateReply = async id => { try{ await api().moderateReply(id,{action:'reported',reason:'Reported from study room'}); toast('Reported to moderation','success'); }catch(e){ toast(e.message,'error'); } };
  window.v68AwardMessage = async (id,p,s) => { try{ await api().awardChatMessage(id,p,s,'Teacher reward'); await v68LoadGroup(appState.selectedGroupId); toast('Student rewarded','success'); }catch(e){ toast(e.message,'error'); } };
  window.v68AwardReply = async (id,p,s) => { try{ await api().awardThreadReply(id,p,s,'Study contribution'); await v68LoadTeacher(); toast('Student rewarded','success'); }catch(e){ toast(e.message,'error'); } };
  window.v68ApproveThread = async id => { try{ await api().updateClassroomThread(id,{approvalStatus:'approved'}); await v68LoadTeacher(); }catch(e){ toast(e.message,'error'); } };
  window.v68ToggleThread = async (id,closed) => { try{ await api().updateClassroomThread(id,{isClosed:closed}); await v68LoadTeacher(); }catch(e){ toast(e.message,'error'); } };
  window.v68ToggleVoice = async () => { try{ if(appState.recording){ appState.recorder?.stop(); appState.recording=false; return; } const stream=await navigator.mediaDevices.getUserMedia({audio:true}); appState.chunks=[]; appState.recorder=new MediaRecorder(stream); appState.recorder.ondataavailable=e=>appState.chunks.push(e.data); appState.recorder.onstop=async()=>{ stream.getTracks().forEach(t=>t.stop()); const file=new File([new Blob(appState.chunks,{type:'audio/webm'})],`voice-${Date.now()}.webm`,{type:'audio/webm'}); appState.attachment=await uploadAny(file); toast('Voice note attached','success'); appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); }; appState.recorder.start(); appState.recording=true; toast('Recording voice note... tap mic again to stop','info'); appState.role==='teacher'?v68RenderTeacher():appState.role==='parent'?v68RenderParent():v68RenderStudent(); }catch(e){ toast('Microphone is blocked or unavailable','error'); } };
  function modal(html){ let m=$('v68-modal'); if(!m){m=document.createElement('div');m.id='v68-modal';document.body.appendChild(m);} m.className='v68-modal'; m.innerHTML=`<div class="v68-modal-card"><button class="v68-close" onclick="v68CloseModal()">×</button>${html}</div>`; }
  window.v68CloseModal=()=>$('v68-modal')?.remove();
  window.v68OpenTopicModal=()=>modal(`<h3>Create Study Topic</h3><p>Student topics wait for teacher approval. Teacher topics open immediately.</p><label>Subject</label><input id="v68-topic-subject" placeholder="Mathematics"><label>Topic</label><input id="v68-topic-title" placeholder="Fractions revision"><label>Question</label><textarea id="v68-topic-content" placeholder="Ask your question..."></textarea><div class="v68-modal-actions"><button class="v68-btn" onclick="v68CloseModal()">Cancel</button><button class="v68-btn primary" onclick="v68SubmitTopic()">Create</button></div>`);
  window.v68SubmitTopic=async()=>{ const g=currentGroup(); const subject=$('v68-topic-subject')?.value?.trim()||'Study Group'; const topic=$('v68-topic-title')?.value?.trim(); const content=$('v68-topic-content')?.value?.trim(); if(!topic||!content)return toast('Topic and question are required','error'); try{ await api().createClassroomThread({classId:g?.classId||null,subject,topic,content,metadata:{approvalStatus:appState.role==='student'?'pending':'approved',source:`${appState.role}-created-topic`}}); v68CloseModal(); appState.role==='teacher'?await v68LoadTeacher():await v68LoadStudent(); }catch(e){ toast(e.message,'error'); } };
  window.v68TeacherNew=()=> appState.tab==='groups'?v68OpenGroupModal():appState.tab==='study'?v68OpenTopicModal():appState.tab==='announce'?v68Broadcast():toast('Choose Groups or Study Rooms first','info');
  window.v68OpenGroupModal=async()=>{ try{ const res=await api().getAvailableMembers(); appState.available=res.data||[]; }catch{ appState.available=[]; } modal(`<h3>Create Group</h3><label>Group name</label><input id="v68-group-name" placeholder="Grade 6 Maths"><label>Description</label><input id="v68-group-desc" placeholder="Optional"><label>Add members</label><div class="v68-member-picker">${appState.available.map(u=>`<label><input type="checkbox" value="${Number(u.id)}"> ${esc(u.name)} <small>• ${esc(u.role)}</small></label>`).join('')}</div><div class="v68-modal-actions"><button class="v68-btn" onclick="v68CloseModal()">Cancel</button><button class="v68-btn primary" onclick="v68CreateGroup()">Create Group</button></div>`); };
  window.v68CreateGroup=async()=>{ const name=$('v68-group-name')?.value?.trim(); if(!name)return toast('Group name required','error'); const ids=[...document.querySelectorAll('.v68-member-picker input:checked')].map(x=>Number(x.value)); try{ await api().createTeacherGroup({name,description:$('v68-group-desc')?.value||'',type:'study',memberUserIds:ids}); v68CloseModal(); await v68LoadTeacher(); }catch(e){ toast(e.message,'error'); } };
  window.v68OpenMembersModal=async id=>{ try{ const [m,a]=await Promise.all([api().getGroupMembers(id),api().getAvailableMembers()]); const selected=new Set((m.data||[]).map(x=>Number(x.User?.id||x.userId))); const available=a.data||[]; modal(`<h3>Manage Members</h3><div class="v68-member-picker">${available.map(u=>`<label><input type="checkbox" value="${Number(u.id)}" ${selected.has(Number(u.id))?'checked':''}> ${esc(u.name)} <small>• ${esc(u.role)}</small></label>`).join('')}</div><div class="v68-modal-actions"><button class="v68-btn" onclick="v68CloseModal()">Cancel</button><button class="v68-btn primary" onclick="v68SaveMembers(${Number(id)})">Save</button></div>`); }catch(e){ toast(e.message,'error'); } };
  window.v68SaveMembers=async id=>{ const ids=[...document.querySelectorAll('.v68-member-picker input:checked')].map(x=>Number(x.value)); try{ await api().updateGroupMembers(id,ids); v68CloseModal(); await v68LoadGroup(id); }catch(e){ toast(e.message,'error'); } };
  window.v68Broadcast=()=>toast('Broadcast saved to announcements workflow. Admin broadcast uses school announcement center.','success');
  window.v9RefreshTeacherChat = window.v68LoadTeacher; window.v9LoadStudentThreads = window.v68LoadStudent;
})();
